### ISSUE TITLE
关于聚合根中删除实体

### ISSUE THREAD

**Issue by rc452860** [meixuesong/aggregate-persistence#11]
聚合根Order中包含OrderItem如果在一个Request中去删除某一个聚合根Order里的OrderItem，是不是得先把聚合根Order全部从数据库里取出来然后和Request里的OrderItem进行对比然后找出删除的数据再去Order里删除对应的OrderItem。

**Comment by meixuesong** [comment]
聚合是数据持久化的单元，所以需要把Order全部取出来。至于对比然后再删除，这是技术实现，可能会有多种技术实现，你说的是其中一种。
