### ISSUE TITLE
再问嵌套实体更新问题

### ISSUE THREAD

**Issue by lizhiwei88** [meixuesong/aggregate-persistence#15]
你好!

如果一个 用户 聚合根里包含一个 地址 实体. 对应数据表是 用户表和地址表.
如果地址实体发生变更. 这种场景如何只单独更新地址数据表,而不更新用户表呢

**Comment by meixuesong** [comment]
这个问题其实跟另一个典型的问题是一样的：订单(order)和订单行(orderItem)，如果订单行修改了，如何更新？在示例代码中有例子https://github.com/meixuesong/aggregate-persistence-sample。最终效果就是orderItem修改了，同时Order也version+1
