### ISSUE TITLE
Change-Tracking 变更追踪Snapshot方案 

### ISSUE THREAD

**Issue by hunao0221** [meixuesong/aggregate-persistence#7]
感谢，之前还想自己实现呢！
请问这有在生产用过吗？

另外， 聚合根需要实现`Versionable`， 然后实现`getVerison()`方法.  
看了simple，对于这个verison没有看懂，需要手动更新它的值以及需要持久化它吗？

**Comment by meixuesong** [comment]
有几个大厂的项目在用。
version是帮助实现乐观锁。
