### ISSUE TITLE
关于version很别扭的用法

### ISSUE THREAD

**Issue by hunao0221** [meixuesong/aggregate-persistence#8]
在创建聚合根时，将verison 设置成了`Versionable.NEW_VERSION`也就是0，然后在仓储的save()方法中通过verison判断该聚合根是不是新的，以执行insert或者update。 
对于乐观锁而言，在update的时候更新它的值为`version + 1` 也是很正常的操作。
我看了simple中Order的insert，是直接将verison设置成了1， 这里就觉得特别的别捏。个人认为`isNew()`不应该直接用乐观锁的值来判断，但是又没有想到其他的办法，不知道作者有没有其他的想法。
```xml
  <insert id="insert" parameterType="com.github.meixuesong.order.dao.OrderDO">
    insert into sale_order (id, create_time, customer_id,
      total_price, total_payment, status, version
      )
    values (#{id,jdbcType=VARCHAR}, #{createTime,jdbcType=TIMESTAMP}, #{customerId,jdbcType=VARCHAR},
      #{totalPrice,jdbcType=DECIMAL}, #{totalPayment,jdbcType=DECIMAL}, #{status,jdbcType=TINYINT}, 1
      )
  </insert>
```

**Comment by meixuesong** [comment]
对于Domain层，不用关心version，所以new object时就是默认值0或者显式赋值Versionable.NEW_VERSION

对于Repository层，需要关心version。唯一你觉得别扭的是直接赋值1了。其实达成共识就好，Repository每次操作都会+1，不论insert还是update。 所以对于insert, 就是0+1
