### ISSUE TITLE
对于复杂的聚合实体，如何更新？

### ISSUE THREAD

**Issue by haozhiqianga** [meixuesong/aggregate-persistence#9]
对于一个聚合根A包含聚合根B，聚合根B包含实体C，更新C中的某条数据，该如何操作？
传统方法：给定参数1（ B和C的标识id），给定参数2（C的数据），根据参数1和参数2更新该条数据。 
如何采用更新聚合根的方法，是不是过于复杂了？

如果构造一个聚合根对象A，只包含各级实体的id（聚合根B ID）， 以及最后一级实体的 数据和标识ID（实体C）， 更新该对象 的方法是否可行？而不是更新整个“聚合根A”

**Comment by meixuesong** [comment]
聚合就是持久化的单元，所以不存在“聚合根A包含聚合根B”的情况。

**Comment by rc452860** [comment]
多层聚合好像没法判断
